name: SMACK CI

on: [push, pull_request]

jobs:
  #check-regressions:
  #  runs-on: ubuntu-20.04
  #  strategy:
  #    matrix:
  #      travis_env:
  #        [
  #          "--exhaustive --folder=c/basic",
  #          "--exhaustive --folder=c/data",
  #          "--exhaustive --folder=c/ntdrivers-simplified",
  #          "--exhaustive --folder=c/ntdrivers",
  #          "--exhaustive --folder=c/bits",
  #          "--exhaustive --folder=c/float",
  #          "--exhaustive --folder=c/locks",
  #          "--exhaustive --folder=c/contracts",
  #          "--exhaustive --folder=c/simd",
  #          "--exhaustive --folder=c/memory-safety",
  #          "--exhaustive --folder=c/pthread",
  #          "--exhaustive --folder=c/pthread_extras",
  #          "--exhaustive --folder=c/strings",
  #          "--exhaustive --folder=c/special",
  #          "--exhaustive --folder=rust/array --languages=rust",
  #          "--exhaustive --folder=rust/basic --languages=rust",
  #          "--exhaustive --folder=rust/box --languages=rust",
  #          "--exhaustive --folder=rust/functions --languages=rust",
  #          "--exhaustive --folder=rust/generics --languages=rust",
  #          "--exhaustive --folder=rust/loops --languages=rust",
  #          "--exhaustive --folder=rust/panic --languages=rust",
  #          "--exhaustive --folder=rust/recursion --languages=rust",
  #          "--exhaustive --folder=rust/structures --languages=rust",
  #          "--exhaustive --folder=rust/vector --languages=rust",
  #          "--exhaustive --folder=rust/cargo/** --languages=cargo --threads=1",
  #          "--exhaustive --folder=llvm --languages=llvm-ir"
  #        ]
  #  steps:
  #    - uses: actions/checkout@v2

  #    - name: install dependencies
  #      env:
  #        GITHUB_ACTIONS: true
  #      run: INSTALL_DEV_DEPENDENCIES=1 INSTALL_RUST=1 ./bin/build.sh

  #    - name: format checking
  #      run: |
  #        ./format/run-clang-format.py -r lib/smack include/smack tools share/smack/include share/smack/lib test examples
  #        flake8 test/regtest.py share/smack/ --extend-exclude share/smack/svcomp/,share/smack/reach.py
  #    
  #    - name: compile and test
  #      env:
  #        TRAVIS_ENV: ${{ matrix.travis_env }}
  #      run: ./bin/build.sh
  check-regressions-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: import/setup environment variables
        run: |
          export TMP_VERSION_FILE="$TMPDIR"/versions
          cp bin/versions "$TMP_VERSION_FILE"
          sed -i"" -e "s/\"//g" "$TMP_VERSION_FILE"
          cat "$TMP_VERSION_FILE" >> $GITHUB_ENV
          export ROOT_DIR="$PWD"/../
          export DEPS_DIR="$ROOT_DIR"/smack-deps
          echo "BOOGIE_DIR=$DEPS_DIR/boogie" >> $GITHUB_ENV
          echo "CORRAL_DIR=$DEPS_DIR/corral" >> $GITHUB_ENV
          echo "SMACKENV=$ROOT_DIR/smack.environment" >> $GITHUB_ENV

      - name: install build/test dependencies
        run: |
          ls /Applications/Xcode.app/Contents/Developer/Platforms/
          exit 1
          brew install ninja
          brew install boost
          brew install rustup
          rustup toolchain install ${{ env.RUST_VERSION }}
          cargo install rustfilt
          sudo pip3 install PyYAML toml psutil

      - name: install llvm
        # Shaobo: we should've been able to use homebrew to install LLVM but
        # there isn't a llvm@10 tap.
        # TODO: switch back to homebrew once we upgrade SMACK to support LLVM
        # 11.
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-apple-darwin.tar.xz
          tar -xf clang+llvm-10.0.0-x86_64-apple-darwin.tar.xz

      - name: install backends
        run: |
          brew install z3
          dotnet tool install Boogie --tool-path ${{ env.BOOGIE_DIR }} --version ${{ env.BOOGIE_VERSION }}
          dotnet tool install Corral --tool-path ${{ env.CORRAL_DIR }} --version ${{ env.CORRAL_VERSION }}
          echo export PATH=\"${{ env.BOOGIE_DIR }}:\$PATH\" >> ${{ env.SMACKENV }}
          echo export PATH=\"${{ env.CORRAL_DIR }}:\$PATH\" >> ${{ env.SMACKENV }}

      - name: build
        run: |
          export PATH="$PWD"/clang+llvm-10.0.0-x86_64-apple-darwin/bin:$PATH
          clang --version
          git submodule init
          git submodule update
          mkdir -p "$PWD"/build
          cd "$PWD"/build
          cmake -DCMAKE_BUILD_TYPE=Debug .. -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          ninja
          sudo ninja install

      - name: test
        run: |
          source ${{ env.SMACKENV }}
          export PATH="$PWD"/clang+llvm-10.0.0-x86_64-apple-darwin/bin:$PATH
          export CPATH=/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1:$CPATH
          clang-10 --version
          smack -h
          smack test/./c/basic/ase_example.c -v
          cd test
          ./regtest.py
